### PR TITLE
Text analyzer

### PR DESCRIPTION
**Pull request by mickey-ichi**

### CODE REVIEW

**Comment by hshindo** [comment]
Thank you for your pull-request. It works well.
Currently, it seems jukainlp-web is the same as react-nlp example. Am I correct?

If there is any difference, please let me know.

**Comment by mickey-ichi** [comment]
@hshindo 
Yes, examples on two options are the same

**Comment by hshindo** [comment]
OK, I got it.
Thank you very much for your great job!

**Comment by mickey-ichi** [comment]
OK, Thank you

**Pull request merged**
